config/routes.rb
Seulixo::Application.routes.draw do
  resources :localidades

  root :to => "localidades#index"

end

app/models/idh.rb
#encoding: UTF-8
require "csv"

class Idh < ActiveRecord::Base
  attr_accessible :owner,:idhm,:renda,:longevidade,:educacao,:ano

	def read_in_csv_idh
		csv_text = File.read('saidaIDH.csv')
		csv = CSV.parse(csv_text, :headers => true)
		csv.each do |row|
			row = row.to_hash.with_indifferent_access
			@localidade = Localidade.new
			@localidade.nome = row[:nome]

			lnome = @localidade.nome

			id = Localidade.get_local_id(lnome)

			if id == 0
				@localidade.save
				id = @localidade.id
			end
			row.delete(:nome)
				
			row[:owner] = id		
			Idh.create!(row.to_hash.symbolize_keys)
		end
	end	 


end

app/models/lixo.rb
require "csv"

class Lixo < ActiveRecord::Base
  attr_accessible :owner, :total, :ceu_aberto,:areas_alagadas,:aterro_controlado,:aterro_sanitario
  attr_accessible :compostagem, :triagem,:incineracao,:nao_fixo,:outros,:ano

  	def read_in_csv_lixo
  		csv_text = File.read('saidaLixo.csv')
		csv = CSV.parse(csv_text, :headers => true)
		csv.each do |row|

			row = row.to_hash.with_indifferent_access

			@localidade = Localidade.new
			@localidade.nome = row[:nome]

			lnome = @localidade.nome

			id = Localidade.get_local_id(lnome)
			
			if id == 0	
				@localidade.save
				id = @localidade.id
			end
			row.delete(:nome)
				
			row[:owner] = id		
			Lixo.create!(row.to_hash.symbolize_keys)
		end
	end
 	

  def self.porcentagem 

  end
end

app/models/localidade.rb
require "csv"

class Localidade < ActiveRecord::Base
  attr_accessible :nome, :habitantes
  validates_uniqueness_of :nome

  def read_in_csv_localidade
  	csv_text = File.read('habitantesTotal.csv')
  	csv = CSV.parse(csv_text, :headers => true)
  	
  	csv.each do |row|
      row = row.to_hash.with_indifferent_access
  		@localidade = Localidade.new
  		@localidade.nome = row[:nome]
      @localidade.habitantes = row[:habitantes]
      @localidade.save
  	end	
  end

  def self.get_local_id(param_nome)
  	local = Localidade.where(:nome => param_nome)
  	id = local.to_a.to_param.to_i
  	id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/localidades_controller.rb
class LocalidadesController < ApplicationController
  # GET /localidades
  # GET /localidades.json
  def index
    @localidades = Localidade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @localidades }
    end
  end

  # GET /localidades/1
  # GET /localidades/1.json
  def show
    @localidade = Localidade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @localidade }
    end
  end

  # GET /localidades/new
  # GET /localidades/new.json
  #def new
  #  @localidade = Localidade.new
#
  #  respond_to do |format|
  #    format.html # new.html.erb
  #    format.json { render json: @localidade }
  #  end
  #end

  # GET /localidades/1/edit
  #def edit
   # @localidade = Localidade.find(params[:id])
  #end

  # POST /localidades
  # POST /local###idades.json
  #def create
   # @localidade = Localidade.new(params[:localidade])

    ##respond_to do |format|
    ##  if @localidade.save
    ##    format.html { redirect_to @localidade, notice: 'Localidade was successfully created.' }
    ##    format.json { render json: @localidade, status: :created, location: @localidade }
    ##  else
    ##    format.html { render action: "new" }
    ##    format.json { render json: @localidade.errors, status: :unprocessable_entity }
    ##  end
    ##end
  ##end

  # PUT /localidades/1
  # PUT /localidades/1.json
 ### def update
    ###@localidade = Localidade.find(params[:id])
###
 ###   respond_to do |format|
  ###    if @localidade.update_attributes(params[:localidade])
  ###      format.html { redirect_to @localidade, notice: 'Localidade was successfully updated.' }
  ###      format.json { head :no_content }
  ###    else
  ###      format.html { render action: "edit" }
  ###      format.json { render json: @localidade.errors, status: :unprocessable_entity }
  ###    end
  ###  end
  ###end

  # DELETE /localidades/1
  # DELETE /localidades/1.json
  def destroy
    @localidade = Localidade.find(params[:id])
    @localidade.destroy

    respond_to do |format|
      format.html { redirect_to localidades_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/localidades_helper.rb
module LocalidadesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- saved from url=(0058)http://twitter.github.com/bootstrap/examples/carousel.html -->
<html lang="pt-BR">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>Seulixo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

 <!-- menu -->
<!-- Wrap the .navbar in .container to center it on the page and provide easy way to target it with .navbar-wrapper. -->
    <div class="container navbar-wrapper">

      <div class="navbar navbar-inverse">
        <div class="navbar-inner">
          <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#index">Seu lixo</a>
          <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="dropdown">
                <a href="http://twitter.github.com/bootstrap/examples/carousel.html#" class="dropdown-toggle" data-toggle="dropdown">Detalhes<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#tabela">Tabela</a></li>
                  <li><a href="#treemap">Treemap</a></li>
                  <!-- <li><a href="http://twitter.github.com/bootstrap/examples/carousel.html#">Belém</a></li> -->
                </ul>
              <!-- <li class="active"><a href="#index">Home</a></li>
               --><li><%= link_to "Sobre", "sobre.html" %></li>
              <li><a href="#contact">Contato</a></li>
              <!-- Read about Bootstrap dropdowns at http://twitter.github.com/bootstrap/javascript.html#dropdowns -->
                  <!--<li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="http://twitter.github.com/bootstrap/examples/carousel.html#">Separated link</a></li>
                  <li><a href="http://twitter.github.com/bootstrap/examples/carousel.html#">One more separated link</a></li>
                  -->
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!-- /.navbar-inner -->
      </div><!-- /.navbar -->

    </div><!-- /.container -->
    <!-- /menu -->


    <div class="container marketing" style = "margin-top: 100px">
    <center><h2><p>    Desde que você entrou nesse site, o Brasil coletou
      <br />
      <b><span id="tempo">-</span></b>
      <br />
     <b>TONELADAS</b> de lixo!</p></h2></center>
     <br />
      <h3><p>E de quem é a culpa?</h3></p>
      

  <%= yield %>
  
  <footer>
      <p>© 2012 Company, Inc.</p>
    </footer>
  </div>

  <script>
      contador();
    </script>
</body>
</html>

app/views/localidades/_form.html.erb
<%= form_for(@localidade) do |f| %>
  <% if @localidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@localidade.errors.count, "error") %> prohibited this localidade from being saved:</h2>

      <ul>
      <% @localidade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/localidades/edit.html.erb
<h1>Editing localidade</h1>

<%= render 'form' %>

<%= link_to 'Show', @localidade %> |
<%= link_to 'Back', localidades_path %>

app/views/localidades/index.html.erb
<!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="span4">
         <!-- <img class="img-circle" src="./files/140x140">-->
          <h2>Classificação</h2>
          <div id='table_div'></div>
        </div><!-- /.span4 -->
        <div class="span4">
          <!--<img class="img-circle" src="./files/140x140">-->
          <h2>Lixo coletado</h2><div id="chart_div"></div>
          
        </div><!-- /.span4 -->
        <div class="span4">
          <!--<img class="img-circle" src="./files/140x140">-->
          <h2>Destino do lixo no Brasil</h2>
          <p><div id='pie'></div></p>
        </div><!-- /.span4 -->
      </div><!-- /.row -->

app/views/localidades/new.html.erb
<h1>New localidade</h1>

<%= render 'form' %>

<%= link_to 'Back', localidades_path %>

app/views/localidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @localidade.nome %>
</p>


<%= link_to 'Edit', edit_localidade_path(@localidade) %> |
<%= link_to 'Back', localidades_path %>

app/views/localidades/sobre.html.erb
lalalalalllalallalalalalalallalallalla